import assert from 'node:assert/strict';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const yamlModuleUrl = new URL('../../../tavern_helper_template/node_modules/yaml/dist/index.js', import.meta.url);
const sourcePath = path.join(root, '世界书', '剧情', 'cg-manifest.yaml');
const generatedJsonPath = path.join(root, 'generated', 'cg-manifest.json');
const generatedTsPath = path.join(root, 'generated', 'cg-manifest.generated.ts');
const generatedPredicatePath = path.join(root, 'generated', 'cg-unlock.generated.ts');
const mounterPath = path.join(root, '脚本', 'CG挂载.js');
const manifestStart = '  /* CG_MANIFEST_GENERATED_START */';
const manifestEnd = '  /* CG_MANIFEST_GENERATED_END */';
const predicateStart = '  /* CG_UNLOCK_PREDICATE_GENERATED_START */';
const predicateEnd = '  /* CG_UNLOCK_PREDICATE_GENERATED_END */';

async function parseYaml(text) {
  const { parse } = await import(yamlModuleUrl.href);
  return parse(text);
}

function spoilerLevel(act) {
  if (act <= 2) return 1;
  if (act <= 6) return 2;
  return 3;
}

function replaceGeneratedBlock(source, start, end, body) {
  const from = source.indexOf(start);
  const to = source.indexOf(end);
  if (from < 0 || to < 0 || to < from) throw new Error(`CG挂载.js 缺少生成标记：${start}`);
  return `${source.slice(0, from)}${start}\n${body}\n${source.slice(to)}`;
}

export async function buildCgArtifacts({ release = false } = {}) {
  const source = await parseYaml(await readFile(sourcePath, 'utf8'));
  assert.equal(source.schema_version, 2, 'CG manifest schema_version must be 2');
  assert.equal(source.release, 'v0.6.0', 'CG manifest release must be v0.6.0');
  if (release && /^PENDING_/.test(source.asset_commit)) throw new Error('release gate: asset_commit 仍为 PENDING_ART_BATCH');
  assert.ok(source.asset_commit, 'asset_commit is required');
  assert.ok(Array.isArray(source.items) && source.items.length === 42, 'expected exactly 42 mainline CGs');

  const sceneIndex = JSON.parse(await readFile(path.join(root, 'generated', 'scene-index.json'), 'utf8'));
  const scenes = new Map(sceneIndex.scenes.map(scene => [scene.id, scene]));
  const sceneNumbers = source.items.map(item => Number(item.scene));
  assert.equal(new Set(sceneNumbers).size, sceneNumbers.length, 'CG source scenes must be unique');
  const effectiveCommit = /^PENDING_/.test(source.asset_commit) ? source.preview_asset_commit : source.asset_commit;
  assert.match(effectiveCommit, /^[a-f0-9]{40}$/, 'preview/effective asset commit must be fixed');
  const imagesBase = `https://cdn.jsdelivr.net/gh/${source.asset_repository}@${effectiveCommit}/${source.asset_directory}`;
  const assetRoot = path.resolve(root, '..', '..', 'tavern_helper_template', ...source.asset_directory.split('/'));

  const items = [];
  for (const entry of source.items) {
    const scene = scenes.get(`main:${Number(entry.scene)}`);
    assert.ok(scene, `CG scene missing from scene index: ${entry.scene}`);
    const file = entry.file || `场景${scene.number}.webp`;
    try { await access(path.join(assetRoot, file)); } catch { throw new Error(`CG asset missing: ${file}`); }
    const title = scene.title;
    const alt = (entry.alt || source.alt_template)
      .replaceAll('{scene}', String(scene.number))
      .replaceAll('{title}', title)
      .trim();
    const item = {
      id: `main:${scene.number}:default`,
      campaign_id: 'main',
      scene: scene.number,
      variant: 'default',
      file,
      title,
      alt,
      date: scene.date,
      act: scene.act,
      tags: ['主线', `第${scene.act}幕`],
      unlock: { type: 'scene_completed', scene: scene.number },
      spoiler_level: spoilerLevel(scene.act),
    };
    assert.ok(item.title && item.alt, `${item.id}: title and alt are required`);
    items.push(item);
  }
  items.sort((a, b) => a.scene - b.scene);
  const manifest = {
    schema_version: 2,
    release: source.release,
    asset_commit: source.asset_commit,
    preview_asset_commit: source.preview_asset_commit,
    images_base: imagesBase,
    items,
  };
  const json = `${JSON.stringify(manifest, null, 2)}\n`;
  const ts = `// Generated by cards/Counterfeit/build_tools/build_cg_manifest.mjs. Do not edit.\nexport const CG_MANIFEST = ${JSON.stringify(manifest, null, 2)} as const;\n`;
  const predicateSource = await readFile(path.join(root, 'build_tools', 'cg_unlock_predicate.mjs'), 'utf8');
  const browserPredicate = predicateSource.replace(/^export /gm, '').trim();
  const predicateTypes = `export interface CgStatLike {
  campaign_id?: string;
  current_scene?: number;
  campaign_completed?: boolean;
  mainline_completed?: boolean;
  collection?: { cg_unlocks?: Record<string, boolean> };
}
export type CgUnlockPredicate =
  | { type: 'scene_completed'; scene: number }
  | { type: 'collection_unlock' | 'opening_seen' | 'fact_observed'; unlock_id?: string };
export interface CgManifestItem {
  id: string;
  campaign_id: string;
  scene?: number;
  unlock: CgUnlockPredicate;
  [key: string]: unknown;
}
export interface CgManifestLike { items?: readonly CgManifestItem[] }
`;
  const typedPredicate = predicateSource
    .replace('function campaignIdOf(stat)', 'function campaignIdOf(stat: CgStatLike | null | undefined): string')
    .replace('function completedScene(stat)', 'function completedScene(stat: CgStatLike | null | undefined): number')
    .replace('function hasCollectionUnlock(stat, unlockId)', 'function hasCollectionUnlock(stat: CgStatLike | null | undefined, unlockId: string | undefined): boolean')
    .replace('function evaluateCgUnlockPredicate(unlock, stat, item)', 'function evaluateCgUnlockPredicate(unlock: CgUnlockPredicate | null | undefined, stat: CgStatLike | null | undefined, item: CgManifestItem | null | undefined): boolean')
    .replace('function isCgUnlocked(item, stat)', 'function isCgUnlocked(item: CgManifestItem | null | undefined, stat: CgStatLike | null | undefined): boolean')
    .replace('function pickCgReveal(manifest, prevStat, curStat)', 'function pickCgReveal(manifest: CgManifestLike | null | undefined, prevStat: CgStatLike | null | undefined, curStat: CgStatLike | null | undefined): CgManifestItem | null');
  const predicateTs = `// Generated from build_tools/cg_unlock_predicate.mjs. Do not edit.\n${predicateTypes}\n${typedPredicate}\n`;
  const manifestBody = `  const CG_MANIFEST = ${JSON.stringify(manifest, null, 2).replaceAll('\n', '\n  ')};`;
  const predicateBody = browserPredicate.split('\n').map(line => `  ${line}`).join('\n');
  let mounter = await readFile(mounterPath, 'utf8');
  mounter = replaceGeneratedBlock(mounter, manifestStart, manifestEnd, manifestBody);
  mounter = replaceGeneratedBlock(mounter, predicateStart, predicateEnd, predicateBody);
  return { manifest, json, ts, predicateTs, mounter };
}

export async function run({ check = false, release = false } = {}) {
  const built = await buildCgArtifacts({ release });
  const expected = new Map([
    [generatedJsonPath, built.json],
    [generatedTsPath, built.ts],
    [generatedPredicatePath, built.predicateTs],
    [mounterPath, built.mounter],
  ]);
  if (check) {
    const stale = [];
    for (const [file, content] of expected) {
      let actual = null;
      try { actual = await readFile(file, 'utf8'); } catch {}
      if (actual !== content) stale.push(path.relative(root, file));
    }
    if (stale.length) throw new Error(`CG manifest artifacts stale or missing: ${stale.join(', ')}`);
    console.log(`CG manifest check passed: 42 items, asset_commit=${built.manifest.asset_commit}`);
    return;
  }
  for (const [file, content] of expected) {
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, content, 'utf8');
  }
  console.log(`CG manifest generated: 42 items, asset_commit=${built.manifest.asset_commit}`);
}

const invokedPath = process.argv[1] ? pathToFileURL(path.resolve(process.argv[1])).href : '';
if (import.meta.url === invokedPath) {
  await run({ check: process.argv.includes('--check'), release: process.argv.includes('--release') });
}
